# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 03:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric or contain any of the following ". @ + -"', regex='^[a-zA-z0-9.+-]*$')]),
        ),
    ]
